# Generated by Django 5.1.3 on 2025-03-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='request',
            name='rating',
        ),
    ]
