# Generated by Django 5.1.3 on 2025-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_clientrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='category',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_request_images/'),
        ),
    ]
