# Generated by Django 5.1.3 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_clientrequest_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
